.TH "AccountStatusInfo" 3 "Mon Jun 11 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AccountStatusInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccountStatusInfo\fP (uint8_t ttype_)"
.br
.ti -1c
.RI "\fBAccountStatusInfo\fP (uint8_t ttype_, uint16_t abank_, uint32_t auser_, uint32_t amsid_, uint32_t ttime_, uint16_t bbank_, uint32_t buser_, uint16_t status_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBttype\fP"
.br
.RI "\fIcommand type \fP"
.ti -1c
.RI "uint16_t \fBabank\fP {0}"
.br
.RI "\fIsource node \fP"
.ti -1c
.RI "uint32_t \fBauser\fP {0}"
.br
.RI "\fIsource user \fP"
.ti -1c
.RI "uint32_t \fBamsid\fP {0}"
.br
.RI "\fImsg id \fP"
.ti -1c
.RI "uint32_t \fBttime\fP {0}"
.br
.RI "\fItime \fP"
.ti -1c
.RI "uint16_t \fBbbank\fP {0}"
.br
.RI "\fIdest node \fP"
.ti -1c
.RI "uint32_t \fBbuser\fP {0}"
.br
.RI "\fIdest user \fP"
.ti -1c
.RI "uint16_t \fBstatus\fP {0}"
.br
.RI "\fIaccount status \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 536 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
