.TH "accountresponse" 3 "Mon May 28 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
accountresponse \- Struct data for get_me and get_accout response\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuser_t\fP \fBusera\fP"
.br
.ti -1c
.RI "\fBuser_t\fP \fBglobalusera\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct data for get_me and get_accout response\&. 
.PP
Definition at line 8 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
