.TH "BlockCommand" 3 "Tue Jun 19 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIBlockCommand\fP\&.
.PP
Inherited by \fBBroadcastMsg\fP, \fBChangeNodeKey\fP, \fBConnected\fP, \fBCreateAccount\fP, \fBCreateNode\fP, \fBGetAccount\fP, \fBGetAccounts\fP, \fBGetBlock\fP, \fBGetBlocks\fP, \fBGetBroadcastMsg\fP, \fBGetFields\fP, \fBGetLog\fP, \fBGetMessage\fP, \fBGetMessageList\fP, \fBGetSignatures\fP, \fBGetTransaction\fP, \fBGetVipKeys\fP, \fBLogAccount\fP, \fBRetrieveFunds\fP, \fBSendMany\fP, \fBSendOne\fP, \fBSetAccountKey\fP, \fBSetAccountStatus\fP, \fBSetNodeStatus\fP, \fBTransactionAccepted\fP, \fBTransactionFailed\fP, \fBUnsetAccountStatus\fP, and \fBUnsetNodeStatus\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 129 of file interfaces\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
