.TH "BroadcastFileHeader" 3 "Tue Jun 12 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BroadcastFileHeader \- Header data user in get broadcast command\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBpath\fP"
.br
.ti -1c
.RI "uint32_t \fBlpath\fP"
.br
.ti -1c
.RI "uint32_t \fBfileSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header data user in get broadcast command\&. 
.PP
Definition at line 300 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
