.TH "ChangeNodeKeyData" 3 "Tue Jun 12 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChangeNodeKeyData \- Change Node Key command data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChangeNodeKeyData\fP (uint16_t node_, uint32_t srcUser_, uint32_t msgId_, uint32_t txnTime_, uint16_t dstNode_, uint8_t pubKey_[32])"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBChangeNodeKeyInfo\fP \fBinfo\fP"
.br
.ti -1c
.RI "unsigned char \fBsign\fP [64]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Change Node Key command data\&. 
.PP
Definition at line 347 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
