.TH "ChangeNodeKeyData" 3 "Thu Aug 30 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChangeNodeKeyData \- Change Node Key command data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChangeNodeKeyData\fP (uint16_t node_, uint32_t srcUser_, uint32_t msgId_, uint32_t txnTime_, uint16_t dstNode_, uint8_t pubKey_[32])"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBttype\fP {TXSTYPE_BKY}"
.br
.RI "\fIcommand type \fP"
.ti -1c
.RI "uint16_t \fBsrc_node\fP {0}"
.br
.RI "\fIsource node \fP"
.ti -1c
.RI "uint32_t \fBsrc_user\fP {0}"
.br
.RI "\fIsource user \fP"
.ti -1c
.RI "uint32_t \fBmsg_id\fP {0}"
.br
.RI "\fIuser message id \fP"
.ti -1c
.RI "uint32_t \fBttime\fP {0}"
.br
.RI "\fItime \fP"
.ti -1c
.RI "uint16_t \fBdst_node\fP {0}"
.br
.RI "\fIdestination node \fP"
.ti -1c
.RI "uint8_t \fBnode_new_key\fP [32]"
.br
.RI "\fInew node key \fP"
.ti -1c
.RI "unsigned char \fBsign\fP [64]"
.br
.ti -1c
.RI "uint8_t \fBold_public_key\fP [32]"
.br
.RI "\fIold public key \fP"
.in -1c
.SH "Detailed Description"
.PP 
Change Node Key command data\&. 

Broadcast file format for each block: \fBSendBroadcastInfo\fP Message (floating size = \fBSendBroadcastInfo\&.msg_length\fP) \fBGetBroadcastAdditionalData\fP 
.PP
Definition at line 336 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
