.TH "CommandHandler" 3 "Thu Aug 30 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandHandler \- Base class for all command handlers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <commandhandler\&.h>\fP
.PP
Inherits \fBICommandHandler\fP\&.
.PP
Inherited by \fBBroadcastMsgHandler\fP, \fBChangeNodeKeyHandler\fP, \fBCreateAccountHandler\fP, \fBCreateNodeHandler\fP, \fBGetAccountHandler\fP, \fBGetAccountsHandler\fP, \fBGetBlockHandler\fP, \fBGetBlocksHandler\fP, \fBGetBroadcastMsgHandler\fP, \fBGetLogHandler\fP, \fBGetMessageHandler\fP, \fBGetMessageListHandler\fP, \fBGetSignaturesHandler\fP, \fBGetTransactionHandler\fP, \fBGetVipKeysHandler\fP, \fBLogAccountHandler\fP, \fBRetrieveFundsHandler\fP, \fBSendManyHandler\fP, \fBSendOneHandler\fP, \fBSetAccountKeyHandler\fP, \fBSetAccountStatusHandler\fP, \fBSetNodeStatusHandler\fP, \fBUnsetAccountStatusHandler\fP, and \fBUnsetNodeStatusHandler\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCommitResult\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandHandler\fP (\fBoffice\fP &\fBoffice\fP, boost::asio::ip::tcp::socket &socket)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "virtual void \fBexecute\fP (std::unique_ptr< \fBIBlockCommand\fP > command, const \fBuser_t\fP &usera) override"
.br
.RI "\fIExecute command\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCommitResult\fP \fBcommitChanges\fP (\fBIBlockCommand\fP &command)"
.br
.ti -1c
.RI "template<typename CommandType > std::unique_ptr< CommandType > \fBinit\fP (std::unique_ptr< \fBIBlockCommand\fP > command)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBoffice\fP & \fBm_offi\fP"
.br
.RI "\fIReference to office object\&. \fP"
.ti -1c
.RI "boost::asio::ip::tcp::socket & \fBm_socket\fP"
.br
.RI "\fISocket for connection with client\&. \fP"
.ti -1c
.RI "\fBuser_t\fP \fBm_usera\fP"
.br
.RI "\fICurrent user blockchain data\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Base class for all command handlers\&. 
.PP
Definition at line 15 of file commandhandler\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CommandHandler::CommandHandler (\fBoffice\fP & office, boost::asio::ip::tcp::socket & socket)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIoffice\fP Office object\&. 
.br
\fIsocket\fP Socket connected with client\&. 
.RE
.PP

.PP
Definition at line 8 of file commandhandler\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void CommandHandler::execute (std::unique_ptr< \fBIBlockCommand\fP > command, const \fBuser_t\fP & usera)\fC [override]\fP, \fC [virtual]\fP"

.PP
Execute command\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcommand\fP Command which dhould be executed\&. 
.br
\fIusera\fP User data\&. 
.RE
.PP

.PP
Implements \fBICommandHandler\fP\&.
.PP
Definition at line 13 of file commandhandler\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
