.TH "CommandService" 3 "Mon Jun 11 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandService \- Command service\&. It execute proper action for commnads\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <commandservice\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandService\fP (\fBoffice\fP &\fBoffice\fP, boost::asio::ip::tcp::socket &socket)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "void \fBonExecute\fP (std::unique_ptr< \fBIBlockCommand\fP > command)"
.br
.RI "\fIexecute method which invokes command handler\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Command service\&. It execute proper action for commnads\&. 
.PP
Definition at line 36 of file commandservice\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CommandService::CommandService (\fBoffice\fP & office, boost::asio::ip::tcp::socket & socket)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIoffice\fP Office object\&. 
.br
\fIsocket\fP Socket connected with client\&. 
.RE
.PP

.PP
Definition at line 12 of file commandservice\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
