.TH "commandresponse" 3 "Mon Jul 2 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
commandresponse \- Struct data for all command which are changed blockchain data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuser_t\fP \fBusera\fP"
.br
.ti -1c
.RI "uint32_t \fBmsid\fP"
.br
.ti -1c
.RI "uint32_t \fBmpos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct data for all command which are changed blockchain data\&. 
.PP
Definition at line 14 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
