.TH "ConnectedInfo" 3 "Tue Jun 12 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConnectedInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectedInfo\fP (uint16_t port_, uint32_t ip_address_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBttype\fP {TXSTYPE_CON}"
.br
.RI "\fIcommand type \fP"
.ti -1c
.RI "uint16_t \fBport\fP {0}"
.br
.RI "\fIport number \fP"
.ti -1c
.RI "uint32_t \fBip_address\fP {0}"
.br
.RI "\fIip address \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 501 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
