.TH "CreateNodeHandler" 3 "Wed Jul 4 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CreateNodeHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommandHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreateNodeHandler\fP (\fBoffice\fP &\fBoffice\fP, boost::asio::ip::tcp::socket &socket)"
.br
.ti -1c
.RI "virtual void \fBonInit\fP (std::unique_ptr< \fBIBlockCommand\fP > command) override"
.br
.RI "\fIInt command event\&. It prepare data's needed to execute command\&. If 'command' casting is needed it should be performed in it\&. \fP"
.ti -1c
.RI "virtual void \fBonExecute\fP () override"
.br
.RI "\fIExecution event\&. It executes actual command and commit it to blockchain\&. \fP"
.ti -1c
.RI "virtual void \fBonValidate\fP () override"
.br
.RI "\fIValidation event\&. It performs command specific validation\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 12 of file createnodehandler\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CreateNodeHandler::onInit (std::unique_ptr< \fBIBlockCommand\fP > command)\fC [override]\fP, \fC [virtual]\fP"

.PP
Int command event\&. It prepare data's needed to execute command\&. If 'command' casting is needed it should be performed in it\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcommand\fP Unique Pointer with command which should be executed\&. 
.RE
.PP

.PP
Implements \fBICommandHandler\fP\&.
.PP
Definition at line 10 of file createnodehandler\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
