.TH "CreateAccountData" 3 "Tue Jun 19 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CreateAccountData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreateAccountData\fP (uint16_t srcNode_, uint32_t srcUser_, uint32_t msgId_, uint32_t txnTime_, uint16_t destNode_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCreateAccountInfo\fP \fBinfo\fP"
.br
.ti -1c
.RI "unsigned char \fBsign\fP [64]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 197 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
