.TH "CreateAccountInfo" 3 "Mon Jun 11 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CreateAccountInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreateAccountInfo\fP (uint16_t srcNode, uint32_t srcUser, uint32_t msgId, uint32_t txnTime, uint16_t destNode)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBttype\fP {TXSTYPE_USR}"
.br
.RI "\fIcommand type \fP"
.ti -1c
.RI "uint16_t \fBsrc_node\fP {0}"
.br
.RI "\fIsource node \fP"
.ti -1c
.RI "uint32_t \fBsrc_user\fP {0}"
.br
.RI "\fIsource user \fP"
.ti -1c
.RI "uint32_t \fBmsg_id\fP {0}"
.br
.RI "\fIuser message id \fP"
.ti -1c
.RI "uint32_t \fBttime\fP {0}"
.br
.RI "\fItime \fP"
.ti -1c
.RI "uint16_t \fBdst_node\fP {0}"
.br
.RI "\fIdestination node \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 181 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
