.TH "CreateNodeData" 3 "Thu Jun 14 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CreateNodeData \- Full struct data for create_node command with signature\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreateNodeData\fP (uint16_t abank_, uint32_t auser_, uint32_t amsid_, uint32_t ttime_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCreateNodeInfo\fP \fBdata\fP"
.br
.ti -1c
.RI "unsigned char \fBsign\fP [64]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Full struct data for create_node command with signature\&. 
.PP
Definition at line 133 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
