.TH "DataPrinter" 3 "Mon Jul 2 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataPrinter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDatPrinter\fP, \fBHdrPrinter\fP, \fBHlogPrinter\fP, \fBInxPrinter\fP, \fBLogPrinter\fP, \fBMsgListPrinter\fP, \fBMsgPrinter\fP, \fBSignaturesPrinter\fP, \fBSrvPrinter\fP, \fBUndoPrinter\fP, and \fBVipPrinter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPrinter\fP (const std::string &filepath)"
.br
.ti -1c
.RI "virtual void \fBprintJson\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBprintString\fP ()=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_filepath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file dataprinter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
