.TH "GetAccountsData" 3 "Sat Jun 16 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetAccountsData \- Data struct for get_accounts command\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetAccountsData\fP (uint16_t srcNode, uint32_t srcUser, uint32_t txnTime, uint32_t blockNo, uint16_t destNode)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGetAccountsInfo\fP \fBinfo\fP"
.br
.RI "\fIinfo data struct \fP"
.ti -1c
.RI "unsigned char \fBsign\fP [64]"
.br
.RI "\fIsignature \fP"
.in -1c
.SH "Detailed Description"
.PP 
Data struct for get_accounts command\&. 
.PP
Definition at line 235 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
