.TH "GetBroadcastAdditionalData" 3 "Tue Jun 5 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetBroadcastAdditionalData \- Rest of broadcast response, after header and message\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBsign\fP [64]"
.br
.RI "signature "
.ti -1c
.RI "uint8_t \fBhash\fP [SHA256_DIGEST_LENGTH]"
.br
.RI "users block hash "
.ti -1c
.RI "uint8_t \fBpkey\fP [SHA256_DIGEST_LENGTH]"
.br
.RI "public key "
.ti -1c
.RI "uint32_t \fBmsid\fP"
.br
.RI "id of last transaction "
.ti -1c
.RI "uint32_t \fBmpos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Rest of broadcast response, after header and message\&. 
.PP
Definition at line 307 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
