.TH "GetBlockInfo" 3 "Wed Jun 13 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetBlockInfo \- Get block info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetBlockInfo\fP (uint16_t srcNode, uint32_t srcUser, uint32_t block_, uint32_t txnTime)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBttype\fP {TXSTYPE_NDS}"
.br
.RI "\fIcommand type \fP"
.ti -1c
.RI "uint16_t \fBsrc_node\fP {0}"
.br
.RI "\fIsource node \fP"
.ti -1c
.RI "uint32_t \fBsrc_user\fP {0}"
.br
.RI "\fIsource user \fP"
.ti -1c
.RI "uint32_t \fBblock\fP {0}"
.br
.RI "\fIblock no\&. \fP"
.ti -1c
.RI "uint32_t \fBttime\fP {0}"
.br
.RI "\fItime \fP"
.in -1c
.SH "Detailed Description"
.PP 
Get block info\&. 
.PP
Definition at line 352 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
