.TH "GetBlockHandler" 3 "Sat Jun 16 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetBlockHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommandHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetBlockHandler\fP (\fBoffice\fP &\fBoffice\fP, boost::asio::ip::tcp::socket &socket)"
.br
.ti -1c
.RI "virtual void \fBonInit\fP (std::unique_ptr< \fBIBlockCommand\fP > command) override"
.br
.RI "\fIInt command event\&. It prepare data's needed to execute command\&. If 'command' casting is needed it should be performed in it\&. \fP"
.ti -1c
.RI "virtual void \fBonExecute\fP () override"
.br
.RI "\fIExecution event\&. It execute actual command and commiting it to blockchain\&. \fP"
.ti -1c
.RI "virtual bool \fBonValidate\fP () override"
.br
.RI "\fIValidtaion event\&. It execute validation of data if it contain all proper value\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 12 of file getblockhandler\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void GetBlockHandler::onInit (std::unique_ptr< \fBIBlockCommand\fP > command)\fC [override]\fP, \fC [virtual]\fP"

.PP
Int command event\&. It prepare data's needed to execute command\&. If 'command' casting is needed it should be performed in it\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcommand\fP Unique Pointer with command which should be executed\&. 
.RE
.PP

.PP
Implements \fBICommandHandler\fP\&.
.PP
Definition at line 11 of file getblockhandler\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
