.TH "GetBroadcastInfo" 3 "Mon Jun 4 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetBroadcastInfo \- Get broadcast info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetBroadcastInfo\fP (uint16_t srcNode, uint32_t srcUser, uint32_t txnTime, uint32_t block_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBttype\fP {TXSTYPE_BLG}"
.br
.RI "command type "
.ti -1c
.RI "uint16_t \fBsrc_node\fP {0}"
.br
.RI "source node "
.ti -1c
.RI "uint32_t \fBsrc_user\fP {0}"
.br
.RI "source user "
.ti -1c
.RI "uint32_t \fBblock\fP {0}"
.br
.RI "block no\&. "
.ti -1c
.RI "uint32_t \fBttime\fP {0}"
.br
.RI "time "
.in -1c
.SH "Detailed Description"
.PP 
Get broadcast info\&. 
.PP
Definition at line 275 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
