.TH "GetLogInfo" 3 "Wed Jul 4 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetLogInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetLogInfo\fP (uint16_t node_, uint32_t user_, uint32_t from_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBttype\fP {TXSTYPE_LOG}"
.br
.RI "\fIcommand type \fP"
.ti -1c
.RI "uint16_t \fBnode\fP {0}"
.br
.RI "\fIsource node \fP"
.ti -1c
.RI "uint32_t \fBuser\fP {0}"
.br
.RI "\fIsource user \fP"
.ti -1c
.RI "uint32_t \fBfrom\fP {0}"
.br
.RI "\fIfrom time \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 437 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
