.TH "GetMessageListInfo" 3 "Mon Jun 11 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetMessageListInfo \- Get list of message info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetMessageListInfo\fP (uint16_t srcNode, uint32_t srcUser, uint32_t txnTime, uint32_t block_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBttype\fP {TXSTYPE_MGS}"
.br
.RI "\fIcommand type \fP"
.ti -1c
.RI "uint16_t \fBsrc_node\fP {0}"
.br
.RI "\fIsource node \fP"
.ti -1c
.RI "uint32_t \fBsrc_user\fP {0}"
.br
.RI "\fIsource user \fP"
.ti -1c
.RI "uint32_t \fBttime\fP {0}"
.br
.RI "\fItime \fP"
.ti -1c
.RI "uint32_t \fBblock\fP {0}"
.br
.RI "\fIblock no\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Get list of message info\&. 
.PP
Definition at line 383 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
