.TH "GetMessageListData" 3 "Tue May 29 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetMessageListData \- Get list of message data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetMessageListData\fP (uint16_t srcNode_, uint32_t srcUser_, uint32_t block_, uint32_t txnTime_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGetMessageListInfo\fP \fBinfo\fP"
.br
.ti -1c
.RI "unsigned char \fBsign\fP [64]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Get list of message data\&. 
.PP
Definition at line 397 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
