.TH "GetSignaturesData" 3 "Mon Jun 4 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetSignaturesData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetSignaturesData\fP (uint16_t abank_, uint32_t auser_, uint32_t ttime_, uint32_t block_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGetSignaturesInfo\fP \fBinfo\fP"
.br
.ti -1c
.RI "unsigned char \fBsign\fP [64]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 600 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
