.TH "GetTransactionResponse" 3 "Mon Jun 4 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetTransactionResponse
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBpath\fP"
.br
.ti -1c
.RI "uint32_t \fBmsid\fP"
.br
.ti -1c
.RI "uint16_t \fBnode\fP"
.br
.ti -1c
.RI "uint16_t \fBtnum\fP"
.br
.ti -1c
.RI "uint16_t \fBlen\fP"
.br
.ti -1c
.RI "uint16_t \fBhnum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 491 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
