.TH "GetTransactionInfo" 3 "Thu Jun 14 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetTransactionInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetTransactionInfo\fP (uint16_t srcNode, uint32_t srcUser, uint32_t time, uint16_t dstNode, uint32_t nodeMsgid, uint32_t pos)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBttype\fP {TXSTYPE_TXS}"
.br
.RI "\fIcommand type \fP"
.ti -1c
.RI "uint16_t \fBsrc_node\fP {0}"
.br
.RI "\fIsource node \fP"
.ti -1c
.RI "uint32_t \fBsrc_user\fP {0}"
.br
.RI "\fIsource user \fP"
.ti -1c
.RI "uint32_t \fBttime\fP {0}"
.br
.RI "\fItime \fP"
.ti -1c
.RI "uint16_t \fBdst_node\fP {0}"
.br
.RI "\fIdest node \fP"
.ti -1c
.RI "uint32_t \fBnode_msgid\fP {0}"
.br
.RI "\fInode msg id \fP"
.ti -1c
.RI "uint16_t \fBposition\fP {0}"
.br
.RI "\fIposition \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 460 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
