.TH "GetTransactionData" 3 "Tue Jun 5 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetTransactionData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetTransactionData\fP (uint16_t srcNode_, uint32_t srcUser_, uint32_t time_, uint16_t dstNode_, uint32_t nodeMsgid_, uint32_t pos_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGetTransactionInfo\fP \fBinfo\fP"
.br
.ti -1c
.RI "unsigned char \fBsign\fP [64]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 481 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
