.TH "hashtree" 3 "Wed Jun 6 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hashtree \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhashtree\fP (void *)"
.br
.ti -1c
.RI "uint32_t \fBbits\fP (uint32_t v)"
.br
.ti -1c
.RI "int \fBhashpath\fP (uint32_t hashnum, uint32_t hashmax, std::vector< uint32_t > &add)"
.br
.ti -1c
.RI "void \fBaddhash\fP (uint8_t *hash, const uint8_t *add)"
.br
.ti -1c
.RI "void \fBhashpathrun\fP (uint8_t *hash, std::vector< \fBhash_s\fP > &hashes)"
.br
.ti -1c
.RI "int \fBupdate\fP (uint8_t *hash)"
.br
.ti -1c
.RI "int \fBfinish\fP (uint8_t *hash)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBhash_s\fP > \fBhashes\fP"
.br
.ti -1c
.RI "\fBhash_s\fP \fBhash_\fP [MAXTREE]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file hash\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
