.TH "Helper::HashSingleVariant" 3 "Tue Jun 12 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helper::HashSingleVariant \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhash_s\fP \fBha\fP {}"
.br
.ti -1c
.RI "uint16_t \fBsvid\fP {0}"
.br
.ti -1c
.RI "uint32_t \fBmsid\fP {0}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file servers\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
