.TH "Helper::Signatures" 3 "Sat Jun 16 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helper::Signatures \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBload\fP (uint32_t path)"
.br
.ti -1c
.RI "void \fBloadSignaturesOk\fP (uint32_t path)"
.br
.ti -1c
.RI "const std::vector< \fBSignature\fP > & \fBgetSignaturesOk\fP ()"
.br
.ti -1c
.RI "const std::vector< \fBSignature\fP > & \fBgetSignaturesNo\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file signatures\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
