.TH "Helper::Block" 3 "Thu Jun 14 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helper::Block \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBreadDataFromHeaderFile\fP ()"
.br
.ti -1c
.RI "bool \fBupdateLastHeader\fP ()"
.br
.ti -1c
.RI "void \fBloadFromHeader\fP (const \fBheader_t\fP &)"
.br
.ti -1c
.RI "\fBheader_t\fP \fBgetHeader\fP ()"
.br
.ti -1c
.RI "\fBServersHeader\fP & \fBgetData\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file block\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
