.TH "Helper::Signature" 3 "Wed Jun 6 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helper::Signature \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBsvid\fP {0}"
.br
.ti -1c
.RI "uint8_t \fBsignature\fP [2 *SHA256_DIGEST_LENGTH]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file signatures\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
