.TH "Helper::ServersHeader" 3 "Wed Jul 4 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helper::ServersHeader \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtoJson\fP (boost::property_tree::ptree &\fBnode\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBversion\fP {0}"
.br
.ti -1c
.RI "uint32_t \fBttime\fP {0}"
.br
.ti -1c
.RI "uint32_t \fBmessageCount\fP {0}"
.br
.ti -1c
.RI "uint32_t \fBnodesCount\fP {0}"
.br
.ti -1c
.RI "uint32_t \fBdividendBalance\fP {0}"
.br
.ti -1c
.RI "uint8_t \fBoldHash\fP [SHA256_DIGEST_LENGTH]"
.br
.ti -1c
.RI "uint8_t \fBminHash\fP [SHA256_DIGEST_LENGTH]"
.br
.ti -1c
.RI "uint8_t \fBmsgHash\fP [SHA256_DIGEST_LENGTH]"
.br
.ti -1c
.RI "uint8_t \fBnodHash\fP [SHA256_DIGEST_LENGTH]"
.br
.ti -1c
.RI "uint8_t \fBvipHash\fP [SHA256_DIGEST_LENGTH]"
.br
.ti -1c
.RI "uint8_t \fBnowHash\fP [SHA256_DIGEST_LENGTH]"
.br
.ti -1c
.RI "uint16_t \fBvoteYes\fP {0}"
.br
.ti -1c
.RI "uint16_t \fBvoteNo\fP {0}"
.br
.ti -1c
.RI "uint16_t \fBvoteTotal\fP {0}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file serversheader\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
