.TH "IBlockCommand" 3 "Thu Jun 14 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IBlockCommand \- Base interface for command\&. It combain \fBICommand\fP BlockCommandand \fBIJsonSerialize\fP Interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <interfaces\&.h>\fP
.PP
Inherits \fBICommand\fP, and \fBIJsonSerialize\fP\&.
.PP
Inherited by \fBBlockCommand\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Base interface for command\&. It combain \fBICommand\fP BlockCommandand \fBIJsonSerialize\fP Interface\&. 
.PP
Definition at line 126 of file interfaces\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
