.TH "INetworkClient" 3 "Tue Jun 12 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
INetworkClient \- Interface for class which is responible for client network connection\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <interfaces\&.h>\fP
.PP
Inherited by \fBNetworkClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBconnect\fP ()=0"
.br
.RI "\fIConnect to server if disconnected\&. \fP"
.ti -1c
.RI "virtual bool \fBreconnect\fP ()=0"
.br
.RI "\fIRecconect to server\&. \fP"
.ti -1c
.RI "virtual bool \fBdisConnect\fP ()=0"
.br
.RI "\fIDisconnect to server\&. \fP"
.ti -1c
.RI "virtual bool \fBsendData\fP (uint8_t *buff, int size)=0"
.br
.RI "\fISend data using pointer to bufor and size\&. \fP"
.ti -1c
.RI "virtual bool \fBsendData\fP (std::vector< uint8_t > buff)=0"
.br
.RI "\fISend data using vector data\&. \fP"
.ti -1c
.RI "virtual bool \fBreadData\fP (uint8_t *buff, int size)=0"
.br
.RI "\fIRead data to buffor\&. \fP"
.ti -1c
.RI "virtual bool \fBreadData\fP (char *buff, int size)=0"
.br
.RI "\fIRead data to buffor\&. \fP"
.ti -1c
.RI "virtual bool \fBreadData\fP (std::vector< uint8_t > &buff)=0"
.br
.RI "\fIRead data to vector\&. \fP"
.ti -1c
.RI "virtual bool \fBreadData\fP (int32_t *buff, int size)=0"
.br
.RI "\fIRead data to int\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface for class which is responible for client network connection\&. 
.PP
Definition at line 15 of file interfaces\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
