.TH "MessageListHeader" 3 "Thu Aug 30 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageListHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msglistparser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessageListHeader\fP (uint32_t numOfMsg, uint8_t messageHash[SHA256_DIGEST_LENGTH])"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBnum_of_msg\fP"
.br
.RI "\fInumber of messages (\fBMessageRecord\fP's) \fP"
.ti -1c
.RI "uint8_t \fBmessage_hash\fP [SHA256_DIGEST_LENGTH]"
.br
.RI "\fImessage pack hash \fP"
.in -1c
.SH "Detailed Description"
.PP 
Header of msglist\&.data file 
.PP
Definition at line 11 of file msglistparser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
