.TH "NewAccountData" 3 "Mon Jun 11 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewAccountData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewAccountData\fP (uint32_t userId, uint8_t userPkey[SHA256_DIGEST_LENGTH])"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBuser_id\fP"
.br
.ti -1c
.RI "uint8_t \fBuser_pkey\fP [SHA256_DIGEST_LENGTH]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 207 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
