.TH "NodeStatusData" 3 "Mon Jun 4 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeStatusData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeStatusData\fP (uint8_t ttype_)"
.br
.ti -1c
.RI "\fBNodeStatusData\fP (uint8_t ttype_, uint16_t abank_, uint32_t auser_, uint32_t amsid_, uint32_t ttime_, uint16_t bbank_, uint32_t status_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNodeStatusInfo\fP \fBinfo\fP"
.br
.ti -1c
.RI "unsigned char \fBsign\fP [64]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 577 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
