.TH "node" 3 "Mon Jul 2 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ed25519_public_key \fBpk\fP"
.br
.ti -1c
.RI "uint64_t \fBhash\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBmsha\fP [SHA256_DIGEST_LENGTH]"
.br
.ti -1c
.RI "uint32_t \fBmsid\fP"
.br
.ti -1c
.RI "uint32_t \fBmtim\fP"
.br
.ti -1c
.RI "int64_t \fBweight\fP"
.br
.ti -1c
.RI "uint32_t \fBstatus\fP"
.br
.ti -1c
.RI "uint32_t \fBusers\fP"
.br
.ti -1c
.RI "uint32_t \fBport\fP"
.br
.ti -1c
.RI "uint32_t \fBipv4\fP"
.br
.ti -1c
.RI "std::vector< uint64_t > \fBchanged\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file servers\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
