.TH "options" 3 "Wed Jul 4 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
options \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBprint_version\fP ()"
.br
.ti -1c
.RI "void \fBget\fP (int ac, char *av[])"
.br
.ti -1c
.RI "uint16_t \fBget_svid\fP (std::string peer_address)"
.br
.ti -1c
.RI "void \fBget_address\fP (const std::string &address, std::string &ip, std::string &port, std::string &svid)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBinit\fP"
.br
.ti -1c
.RI "bool \fBfast\fP"
.br
.ti -1c
.RI "bool \fBcomm\fP"
.br
.ti -1c
.RI "int \fBmins\fP"
.br
.ti -1c
.RI "int \fBoffi\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "int \fBsvid\fP"
.br
.ti -1c
.RI "std::string \fBaddr\fP"
.br
.ti -1c
.RI "std::string \fBdnsa\fP"
.br
.ti -1c
.RI "std::string \fBgenesis\fP"
.br
.ti -1c
.RI "std::string \fBviphash\fP"
.br
.ti -1c
.RI "uint32_t \fBipv4\fP"
.br
.ti -1c
.RI "int \fBback\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBpeer\fP"
.br
.ti -1c
.RI "std::string \fBworkdir\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file options\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
