.TH "ResponseHandler" 3 "Thu Jun 14 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResponseHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResponseHandler\fP (\fBsettings\fP &sts)"
.br
.ti -1c
.RI "void \fBonExecute\fP (std::unique_ptr< \fBIBlockCommand\fP > command)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file responsehandler\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
