.TH "SendBroadcastInfo" 3 "Thu Aug 30 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SendBroadcastInfo \- Send Broadcast info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSendBroadcastInfo\fP (uint16_t srcNode, uint32_t srcUser, uint32_t msgId, uint32_t txnTime, uint16_t msgLength)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBttype\fP {TXSTYPE_BRO}"
.br
.RI "\fIcommand type \fP"
.ti -1c
.RI "uint16_t \fBsrc_node\fP {0}"
.br
.RI "\fIsource node \fP"
.ti -1c
.RI "uint32_t \fBsrc_user\fP {0}"
.br
.RI "\fIsource user \fP"
.ti -1c
.RI "uint32_t \fBmsg_id\fP {0}"
.br
.RI "\fIuser message id \fP"
.ti -1c
.RI "uint32_t \fBttime\fP {0}"
.br
.RI "\fItime \fP"
.ti -1c
.RI "uint16_t \fBmsg_length\fP {0}"
.br
.RI "\fImsg_length \fP"
.in -1c
.SH "Detailed Description"
.PP 
Send Broadcast info\&. 
.PP
Definition at line 255 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
