.TH "SendAmountTxnRecord" 3 "Mon Jun 4 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SendAmountTxnRecord \- Vector item, record to store one transaction in send_many message\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSendAmountTxnRecord\fP (uint16_t bank, uint32_t user, int64_t mass)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBdest_node\fP"
.br
.RI "destintaion node "
.ti -1c
.RI "uint32_t \fBdest_user\fP"
.br
.RI "destination user "
.ti -1c
.RI "int64_t \fBamount\fP"
.br
.RI "sending amount "
.in -1c
.SH "Detailed Description"
.PP 
Vector item, record to store one transaction in send_many message\&. 
.PP
Definition at line 170 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
