.TH "SignaturesPrinter" 3 "Thu Jun 14 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SignaturesPrinter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDataPrinter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSignaturesPrinter\fP (const std::string &filepath)"
.br
.ti -1c
.RI "virtual void \fBprintJson\fP () override"
.br
.ti -1c
.RI "virtual void \fBprintString\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file signaturesprinter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
