.TH "tInfo" 3 "Thu Jun 14 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBweight\fP"
.br
.ti -1c
.RI "int64_t \fBdeduct\fP"
.br
.ti -1c
.RI "int64_t \fBfee\fP"
.br
.ti -1c
.RI "uint16_t \fBstat\fP"
.br
.ti -1c
.RI "uint8_t \fBpkey\fP [6]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
