.TH "TransactionFailedInfo" 3 "Tue Jun 19 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionFailedInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransactionFailedInfo\fP (int msgSize)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBttype\fP {TXSTYPE_NON}"
.br
.RI "\fIcommand type \fP"
.ti -1c
.RI "uint32_t \fBmessage_size\fP"
.br
.RI "\fImessage size \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 522 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
