.TH "usertxs" 3 "Thu Aug 30 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usertxs \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBusertxs\fP (uint32_t len)"
.br
.ti -1c
.RI "\fBusertxs\fP (uint8_t *din, int len)"
.br
.ti -1c
.RI "\fBusertxs\fP (uint8_t nttype, uint16_t nabank, uint32_t nauser, uint16_t nbbank, uint32_t nbuser, uint32_t nttime)"
.br
.ti -1c
.RI "\fBusertxs\fP (uint8_t nttype, uint16_t nabank, uint32_t nauser, uint32_t nttime)"
.br
.ti -1c
.RI "\fBusertxs\fP (uint8_t nttype, uint16_t nabank, uint32_t nauser, const char *version)"
.br
.ti -1c
.RI "\fBusertxs\fP (uint8_t nttype, uint16_t nabank, uint32_t nauser, uint32_t namsid, uint32_t nttime, uint16_t nbbank, uint32_t nbuser, int64_t ntmass, uint8_t *ntinfo, const char *text)"
.br
.ti -1c
.RI "uint32_t \fBget_size\fP (char *txs)"
.br
.ti -1c
.RI "bool \fBparse\fP (char *txs)"
.br
.ti -1c
.RI "uint8_t * \fBget_sig\fP (char *buf)"
.br
.ti -1c
.RI "int \fBsign_mlen2\fP ()"
.br
.ti -1c
.RI "void \fBprint_head\fP ()"
.br
.ti -1c
.RI "char * \fBusr\fP (char *buf)"
.br
.ti -1c
.RI "char * \fBvip\fP (char *buf)"
.br
.ti -1c
.RI "char * \fBkey\fP (char *buf)"
.br
.ti -1c
.RI "char * \fBopkey\fP (char *buf)"
.br
.ti -1c
.RI "char * \fBupkey\fP (char *buf)"
.br
.ti -1c
.RI "char * \fBbroadcast\fP (char *buf)"
.br
.ti -1c
.RI "char * \fBtoaddresses\fP (char *buf)"
.br
.ti -1c
.RI "uint32_t \fBnuser\fP (char *buf)"
.br
.ti -1c
.RI "char * \fBnpkey\fP (char *buf)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBttype\fP"
.br
.ti -1c
.RI "uint16_t \fBabank\fP"
.br
.ti -1c
.RI "uint32_t \fBauser\fP"
.br
.ti -1c
.RI "uint32_t \fBamsid\fP"
.br
.ti -1c
.RI "uint32_t \fBttime\fP"
.br
.ti -1c
.RI "uint16_t \fBbbank\fP"
.br
.ti -1c
.RI "uint32_t \fBbuser\fP"
.br
.ti -1c
.RI "int64_t \fBtmass\fP"
.br
.ti -1c
.RI "uint8_t \fBtinfo\fP [32] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}"
.br
.ti -1c
.RI "uint8_t * \fBdata\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file user\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
