.TH "user_s" 3 "Tue May 29 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBmsid\fP"
.br
.ti -1c
.RI "uint32_t \fBtime\fP"
.br
.ti -1c
.RI "uint8_t \fBpkey\fP [SHA256_DIGEST_LENGTH]"
.br
.ti -1c
.RI "uint8_t \fBhash\fP [SHA256_DIGEST_LENGTH]"
.br
.ti -1c
.RI "uint32_t \fBlpath\fP"
.br
.ti -1c
.RI "uint32_t \fBuser\fP"
.br
.ti -1c
.RI "uint16_t \fBnode\fP"
.br
.ti -1c
.RI "uint16_t \fBstat\fP"
.br
.ti -1c
.RI "uint32_t \fBrpath\fP"
.br
.ti -1c
.RI "int64_t \fBweight\fP"
.br
.ti -1c
.RI "uint64_t \fBcsum\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 96 of file default\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
