.TH "usertxs2" 3 "Tue Jun 12 2018" "esc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
usertxs2 \- Full struct data for get_me and get_accout command with signature\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pods\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBusertxs2\fP (uint16_t abank, uint32_t auser, uint16_t bbank, uint16_t buser, uint32_t time)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuserinfo\fP \fBinfo\fP"
.br
.ti -1c
.RI "unsigned char \fBsign\fP [64]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Full struct data for get_me and get_accout command with signature\&. 
.PP
Definition at line 52 of file pods\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for esc from the source code\&.
